### ISSUE TITLE
hot reloading and live reloading

### ISSUE THREAD

**Issue by mouhsnimohamed** [nodegui/react-nodegui-starter#9] opened 2019-08-27 18:45 UTC
How can I enable **Hot reloading** and **Live reloading**

**Comment by a7ul** [comment] 2019-08-27 20:58
Hi @mouhsnimohamed 
Hot reloading and live reloading support is not supported and is WIP.
But you could use a temporary solution till then for live reload.

You could use nodemon.
Just add the following npm script
```
"start:watch": "nodemon -e js,ts,tsx --ignore dist/ --ignore node_modules/ --exec npm start"  

```

**Comment by mouhsnimohamed** [comment] 2019-08-28 18:55
thanks @master-atul that works for me. but I'm wandering how can I build a .exe file for windows users? I searched in docs but didn't find anything about that. I want to make my first app using react-nodegui

**Comment by a7ul** [comment] 2019-08-28 19:41
App Packaging is WIP.  You should hear about it very soon (in few days). 😄   @mouhsnimohamed 
Till then you can start building your app and maybe suggest few improvement or raise PRs containing improvements to this project :)

**Comment by a7ul** [comment] 2019-09-01 22:27
@mouhsnimohamed  App packaging is now ready. I have just released a basic version of it at the moment. You can check it out at https://github.com/nodegui/packer

**Comment by mouhsnimohamed** [comment] 2019-09-02 10:41
awsome! I'll give it a try. thanks

**Comment by a7ul** [comment] 2019-09-02 16:58
Closing this as its a duplicate of https://github.com/nodegui/react-nodegui/issues/5

**Closed as completed by a7ul** 2019-09-02 16:58 UTC
Labels: enhancement

**Comment by sahilrajput03** [comment] 2026-05-01 06:06
> Hi [@mouhsnimohamed](https://github.com/mouhsnimohamed) Hot reloading and live reloading support is not supported and is WIP. But you could use a temporary solution till then for live reload.
> 
> You could use nodemon. Just add the following npm script
> 
> ```
> "start:watch": "nodemon -e js,ts,tsx --ignore dist/ --ignore node_modules/ --exec npm start"  
> ```

I tried to use this but in my typescript project it created infinite loop and the fix was to add `dist` as ignored directory:

```json
"dev": "nodemon -e js,ts,tsx --ignore dist/ --ignore build/ --ignore node_modules/ --exec npm start"
```

Thanks.
